require("david.plugins-setup")

require("david.core.options")
require("david.core.keymaps")
require("david.core.colorscheme")

require("david.plugins.nvim-cmp")
require("david.plugins.comment")
require("david.plugins.nvim-tree")
require("david.plugins.lualine")
require("david.plugins.telescope")
require("david.plugins.lsp.mason")
require("david.plugins.lsp.lspsaga")
require("david.plugins.lsp.lspconfig")
require("david.plugins.lsp.null-ls")
require("david.plugins.autopairs")
require("david.plugins.treesitter")
require("david.plugins.gitsigns")
require("david.plugins.trouble")
